version: 2

models:
  - name: dim_address
    description: "A test for dim address"
    columns:
      - name: ADDRESS_COMPANY_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_company
    description: "A test for dim company"
    columns:
      - name: COMPANY_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_contact
    description: "A test for dim contact"
    columns:
      - name: CONTACT_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_currency
    description: "A test for dim currency"
    columns:
      - name: CURRENCY_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


  - name: dim_deal
    description: "A test for dim deal"
    columns:
      - name: DEAL_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_deal_stages
    description: "A test for dim deal stages"
    columns:
      - name: STAGE_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_user
    description: "A test for dim user"
    columns:
      - name: USER_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

