version: 2

models:
  - name: dim_address
    description: "A test for dim address"
    columns:
      - name: ADDRESS_COMPANY_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_company
    description: "A test for dim company"
    columns:
      - name: COMPANY_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
